### ISSUE TITLE
Unusable in macOS

### ISSUE THREAD

**Issue by agathver** [zairza-cetb/bench-routes-electron#14]
Transparent browser windows don't work properly in macOS without proper designing and native code to implement CSD

**Comment by Harkishen-Singh** [comment]
We have actually given up the transparent background idea since Linux machine support it with `--enable-transparent-visuals --disable-gpu`. But, we have no concrete proof of whether the `electron-packager` will support the transparent background without those flags at the time of building. Same goes for mac.

Only windows will support it. Hence, till we have dropped this idea until we find some reliable approach.

**Comment by agathver** [comment]
Why do you need transparent background? 
Besides transparent backgrounds will crash on Nvidia GPUs on linux regardless of whether you pass --disable-gpu

**Comment by Harkishen-Singh** [comment]
We planned an interactive sidebar which would be translucent like the ones found in macOS (appstore), and hence a transparent window would pave its way to the approach.

**Comment by Harkishen-Singh** [comment]
@agathver please confirm whether this exists in the current commits.

**Comment by agathver** [comment]
Works 👍
